### ISSUE TITLE
WPTAPIError 404

### ISSUE THREAD

**Issue by iDVB** [marcelduran/webpagetest-api#117]
command:
`webpagetest test https://twitter.com/marcelduran -s http://localhost:4000/work/`

error:
```
{
  "error": {
    "name": "WPTAPIError",
    "code": 404,
    "message": "Not Found"
  }
}
```

I can browse to the server at `http://localhost:4000` and submit a test successfully.
this is my config

```
version: "3"
services:

  server:
    image: webpagetest/server:latest
    ports:
      - "4000:80"
    expose:
      - "4000"
    volumes:
      - ./server/locations.ini:/var/www/html/settings/locations.ini

  agent:
    image: webpagetest/agent:latest
    environment:
      SERVER_URL: http://localhost:4000/work/
      LOCATION: Test
    ports:
      - "4001:80"
    network_mode: "host"
    expose:
      - "4001"
    volumes:
      - ./agent/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    depends_on:
      - server
```
